//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALSIEntities : DbContext
    {
        public ALSIEntities()
            : base("name=ALSIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<job_info> job_info { get; set; }
        public DbSet<job_reiew_requistion> job_reiew_requistion { get; set; }
        public DbSet<job_running> job_running { get; set; }
        public DbSet<job_sample> job_sample { get; set; }
        public DbSet<job_sample_group_so> job_sample_group_so { get; set; }
        public DbSet<job_sample_group_so_ignore_code> job_sample_group_so_ignore_code { get; set; }
        public DbSet<job_sample_logs> job_sample_logs { get; set; }
        public DbSet<m_completion_scheduled> m_completion_scheduled { get; set; }
        public DbSet<m_customer> m_customer { get; set; }
        public DbSet<m_customer_address> m_customer_address { get; set; }
        public DbSet<m_customer_contract_person> m_customer_contract_person { get; set; }
        public DbSet<m_role> m_role { get; set; }
        public DbSet<m_specification> m_specification { get; set; }
        public DbSet<m_status> m_status { get; set; }
        public DbSet<m_status_group> m_status_group { get; set; }
        public DbSet<m_template> m_template { get; set; }
        public DbSet<m_title> m_title { get; set; }
        public DbSet<m_type_of_test> m_type_of_test { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<menu_role> menu_role { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<tb_m_component> tb_m_component { get; set; }
        public DbSet<tb_m_detail_spec> tb_m_detail_spec { get; set; }
        public DbSet<tb_m_detail_spec_ref> tb_m_detail_spec_ref { get; set; }
        public DbSet<tb_m_dhs_cas> tb_m_dhs_cas { get; set; }
        public DbSet<tb_m_dhs_library> tb_m_dhs_library { get; set; }
        public DbSet<tb_m_gcms_cas> tb_m_gcms_cas { get; set; }
        public DbSet<tb_m_specification> tb_m_specification { get; set; }
        public DbSet<tb_unit> tb_unit { get; set; }
        public DbSet<template_img> template_img { get; set; }
        public DbSet<template_pa> template_pa { get; set; }
        public DbSet<template_pa_detail> template_pa_detail { get; set; }
        public DbSet<template_seagate_copperwire_coverpage> template_seagate_copperwire_coverpage { get; set; }
        public DbSet<template_seagate_copperwire_img> template_seagate_copperwire_img { get; set; }
        public DbSet<template_seagate_corrosion_coverpage> template_seagate_corrosion_coverpage { get; set; }
        public DbSet<template_seagate_corrosion_img> template_seagate_corrosion_img { get; set; }
        public DbSet<template_seagate_dhs_coverpage> template_seagate_dhs_coverpage { get; set; }
        public DbSet<template_seagate_ftir_coverpage> template_seagate_ftir_coverpage { get; set; }
        public DbSet<template_seagate_gcms_coverpage> template_seagate_gcms_coverpage { get; set; }
        public DbSet<template_seagate_gcms_coverpage_2> template_seagate_gcms_coverpage_2 { get; set; }
        public DbSet<template_seagate_gcms_coverpage_img> template_seagate_gcms_coverpage_img { get; set; }
        public DbSet<template_seagate_hpa_coverpage> template_seagate_hpa_coverpage { get; set; }
        public DbSet<template_seagate_ic_coverpage> template_seagate_ic_coverpage { get; set; }
        public DbSet<template_seagate_lpc_coverpage> template_seagate_lpc_coverpage { get; set; }
        public DbSet<template_seagate_mesa_coverpage> template_seagate_mesa_coverpage { get; set; }
        public DbSet<template_seagate_mesa_img> template_seagate_mesa_img { get; set; }
        public DbSet<template_wd_corrosion_coverpage> template_wd_corrosion_coverpage { get; set; }
        public DbSet<template_wd_corrosion_img> template_wd_corrosion_img { get; set; }
        public DbSet<template_wd_dhs_coverpage> template_wd_dhs_coverpage { get; set; }
        public DbSet<template_wd_ftir_coverpage> template_wd_ftir_coverpage { get; set; }
        public DbSet<template_wd_ftir_coverpage_tmp> template_wd_ftir_coverpage_tmp { get; set; }
        public DbSet<template_wd_gcms_coverpage> template_wd_gcms_coverpage { get; set; }
        public DbSet<template_wd_hpa_for1_coverpage> template_wd_hpa_for1_coverpage { get; set; }
        public DbSet<template_wd_hpa_for3_coverpage> template_wd_hpa_for3_coverpage { get; set; }
        public DbSet<template_wd_ic_coverpage> template_wd_ic_coverpage { get; set; }
        public DbSet<template_wd_ir_coverpage> template_wd_ir_coverpage { get; set; }
        public DbSet<template_wd_lpc_coverpage> template_wd_lpc_coverpage { get; set; }
        public DbSet<template_wd_mesa_coverpage> template_wd_mesa_coverpage { get; set; }
        public DbSet<template_wd_mesa_img> template_wd_mesa_img { get; set; }
        public DbSet<users_login> users_login { get; set; }
        public DbSet<users_responsible> users_responsible { get; set; }
        public DbSet<users_role> users_role { get; set; }
        public DbSet<ws_hash_value> ws_hash_value { get; set; }
        public DbSet<holiday_calendar> holiday_calendar { get; set; }
        public DbSet<users_logged> users_logged { get; set; }
    }
}
