//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_running
    {
        public job_running()
        {
            this.job_info = new HashSet<job_info>();
        }
    
        public int ID { get; set; }
        public string prefix { get; set; }
        public Nullable<int> running_number { get; set; }
    
        public virtual ICollection<job_info> job_info { get; set; }
    }
}
