//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_customer
    {
        public m_customer()
        {
            this.job_info = new HashSet<job_info>();
            this.m_customer_contract_person = new HashSet<m_customer_contract_person>();
            this.m_customer_address = new HashSet<m_customer_address>();
        }
    
        public int ID { get; set; }
        public string customer_code { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public string sub_district { get; set; }
        public string mobile_number { get; set; }
        public string email_address { get; set; }
        public string branch { get; set; }
        public string district { get; set; }
        public string ext { get; set; }
        public string department { get; set; }
        public string province { get; set; }
        public string code { get; set; }
        public string tel_number { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<job_info> job_info { get; set; }
        public virtual ICollection<m_customer_contract_person> m_customer_contract_person { get; set; }
        public virtual ICollection<m_customer_address> m_customer_address { get; set; }
    }
}
