//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_title
    {
        public m_title()
        {
            this.users_login = new HashSet<users_login>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<users_login> users_login { get; set; }
    }
}
