//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_f_ic
    {
        public int id { get; set; }
        public Nullable<int> sample_id { get; set; }
        public string col_1 { get; set; }
        public string col_2 { get; set; }
        public string col_3 { get; set; }
        public string col_4 { get; set; }
        public string col_5 { get; set; }
        public string col_6 { get; set; }
        public string col_7 { get; set; }
        public string col_8 { get; set; }
        public string col_9 { get; set; }
        public string col_10 { get; set; }
        public string col_11 { get; set; }
        public string col_12 { get; set; }
        public string col_13 { get; set; }
        public string col_14 { get; set; }
        public string col_15 { get; set; }
        public string col_16 { get; set; }
        public string col_17 { get; set; }
        public string col_18 { get; set; }
        public string col_19 { get; set; }
        public string col_20 { get; set; }
        public Nullable<int> row_type { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
