//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_seagate_lpc_coverpage
    {
        public int id { get; set; }
        public Nullable<int> sample_id { get; set; }
        public string particle_type { get; set; }
        public string lpc_type { get; set; }
        public Nullable<int> specification_id { get; set; }
        public string b14 { get; set; }
        public string b15 { get; set; }
        public string b16 { get; set; }
        public string b17 { get; set; }
        public string c14 { get; set; }
        public string c15 { get; set; }
        public string c16 { get; set; }
        public string c17 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
        public string d16 { get; set; }
        public string d17 { get; set; }
        public string e14 { get; set; }
        public string e15 { get; set; }
        public string e16 { get; set; }
        public string e17 { get; set; }
        public string f14 { get; set; }
        public string f15 { get; set; }
        public string f16 { get; set; }
        public string f17 { get; set; }
        public string g14 { get; set; }
        public string g15 { get; set; }
        public string g16 { get; set; }
        public string g17 { get; set; }
        public string b21 { get; set; }
        public string b25 { get; set; }
        public string d25 { get; set; }
        public string f25 { get; set; }
        public string b18 { get; set; }
        public string c18 { get; set; }
        public string d18 { get; set; }
        public string e18 { get; set; }
        public string f18 { get; set; }
        public string g18 { get; set; }
        public string b26 { get; set; }
        public string item_visible { get; set; }
        public string ProcedureNo { get; set; }
        public string NumberOfPieces { get; set; }
        public string ExtractionMedium { get; set; }
        public string ExtractionVolume { get; set; }
        public string LiquidParticleCount { get; set; }
        public string SpecificationLimits { get; set; }
        public string Results { get; set; }
        public Nullable<int> RunNumber { get; set; }
        public string Run { get; set; }
        public string type { get; set; }
        public Nullable<double> SurfaceArea { get; set; }
        public Nullable<int> template_type { get; set; }
        public string channel_size { get; set; }
        public Nullable<int> row_state { get; set; }
        public Nullable<int> row_type { get; set; }
        public Nullable<double> df03 { get; set; }
        public Nullable<double> df05 { get; set; }
        public Nullable<double> df06 { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<int> decimal01 { get; set; }
        public Nullable<int> decimal02 { get; set; }
        public Nullable<int> decimal03 { get; set; }
        public Nullable<int> decimal04 { get; set; }
        public Nullable<int> decimal05 { get; set; }
    }
}
