//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_pa
    {
        public int id { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> specification_id { get; set; }
        public string lms { get; set; }
        public string lnmp { get; set; }
        public string lf { get; set; }
        public string doec { get; set; }
        public string dos { get; set; }
        public string customerlimit { get; set; }
        public string gravimetry { get; set; }
        public string lmsp { get; set; }
        public string extractionvalue { get; set; }
        public string lnmsp { get; set; }
        public string eop_g { get; set; }
        public string eop_lmsp { get; set; }
        public string eop_lnmsp { get; set; }
        public string eop_pt { get; set; }
        public string eop_size { get; set; }
        public string eop_value { get; set; }
        public string remark { get; set; }
        public Nullable<int> result { get; set; }
        public string pirtd { get; set; }
        public string iscsa { get; set; }
        public string wspc { get; set; }
        public string tls { get; set; }
        public Nullable<sbyte> ispretreatmentconditioning { get; set; }
        public string pretreatmentconditioning { get; set; }
        public string ispackingtobetested { get; set; }
        public Nullable<sbyte> iscontainer { get; set; }
        public Nullable<int> container_id { get; set; }
        public Nullable<sbyte> isfluid1 { get; set; }
        public Nullable<int> fluid1_id { get; set; }
        public Nullable<sbyte> isfluid2 { get; set; }
        public Nullable<int> fluid2_id { get; set; }
        public Nullable<sbyte> isfluid3 { get; set; }
        public Nullable<int> fluid3_id { get; set; }
        public string tradename { get; set; }
        public string manufacturer { get; set; }
        public string totalquantity { get; set; }
        public Nullable<sbyte> istshb01 { get; set; }
        public Nullable<sbyte> istshb02 { get; set; }
        public Nullable<sbyte> istshb03 { get; set; }
        public string tshb03 { get; set; }
        public string img03 { get; set; }
        public string img02 { get; set; }
        public string img01 { get; set; }
        public Nullable<sbyte> ispots01 { get; set; }
        public string pots01 { get; set; }
        public Nullable<sbyte> isdissolving { get; set; }
        public string dissolving { get; set; }
        public string dissolvingtime { get; set; }
        public Nullable<sbyte> ispressurerinsing { get; set; }
        public Nullable<sbyte> isinternalrinsing { get; set; }
        public Nullable<sbyte> isagitation { get; set; }
        public Nullable<sbyte> iswashquantity { get; set; }
        public string washquantity { get; set; }
        public Nullable<sbyte> isrewashingquantity { get; set; }
        public string rewashingquantity { get; set; }
        public Nullable<sbyte> iswashpressurerinsing { get; set; }
        public Nullable<sbyte> iswashinternalrinsing { get; set; }
        public Nullable<sbyte> iswashagitation { get; set; }
        public string isfiltrationmethod { get; set; }
        public Nullable<int> manufacturer_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public string poresize { get; set; }
        public string diameter { get; set; }
        public Nullable<sbyte> isoven { get; set; }
        public Nullable<sbyte> isdesiccator { get; set; }
        public Nullable<sbyte> isambientair { get; set; }
        public Nullable<sbyte> iseasydry { get; set; }
        public string drytime { get; set; }
        public string temperature { get; set; }
        public Nullable<int> gravimetricalalysis_id { get; set; }
        public string model { get; set; }
        public string balanceresolution { get; set; }
        public string lastcalibration { get; set; }
        public Nullable<sbyte> iszeissaxioimager2 { get; set; }
        public Nullable<sbyte> ismeasuringsoftware { get; set; }
        public Nullable<sbyte> isautomated { get; set; }
        public string automated { get; set; }
        public string totalextractionvolume { get; set; }
        public string lbextractionmethod { get; set; }
        public string numberofcomponents { get; set; }
        public string lbextractiontime { get; set; }
        public string lbmembranetype { get; set; }
        public string wvpc { get; set; }
        public string img04 { get; set; }
        public string lbx { get; set; }
        public string lby { get; set; }
        public string measureddiameter { get; set; }
        public string feretlmsp { get; set; }
        public string feretlnms { get; set; }
        public string feretfb { get; set; }
        public string lms_x { get; set; }
        public string lms_y { get; set; }
        public string lnms_x { get; set; }
        public string lnms_y { get; set; }
        public string lf_x { get; set; }
        public string lf_y { get; set; }
        public string img05 { get; set; }
        public string attachment_ii_01 { get; set; }
        public string attachment_ii_02 { get; set; }
        public string attachment_ii_03 { get; set; }
        public string attachment_ii_04 { get; set; }
        public string param_magnification_01 { get; set; }
        public string param_magnification_02 { get; set; }
        public string param_wd_01 { get; set; }
        public string param_wd_02 { get; set; }
        public string param_eht_01 { get; set; }
        public string param_eht_02 { get; set; }
        public string param_detector_01 { get; set; }
        public string param_detector_02 { get; set; }
        public Nullable<sbyte> iswashUltrasonic { get; set; }
        public Nullable<sbyte> isUltrasonic { get; set; }
        public Nullable<int> rinsing_id { get; set; }
        public Nullable<int> washpressurerinsing_id { get; set; }
        public string per_component_total { get; set; }
        public string per_component_metallicshine { get; set; }
        public string per_membrane_metallicshine { get; set; }
        public Nullable<int> specification_no { get; set; }
        public Nullable<int> operater_name { get; set; }
        public string per_text { get; set; }
        public string img06 { get; set; }
        public string img07 { get; set; }
        public string img08 { get; set; }
        public string img09 { get; set; }
        public string img10 { get; set; }
        public string img11 { get; set; }
        public string attachment_ii_05 { get; set; }
        public string lms_x_r2 { get; set; }
        public string lms_y_r2 { get; set; }
        public string lnms_x_r2 { get; set; }
        public string lnms_y_r2 { get; set; }
        public string lf_x_r2 { get; set; }
        public string lf_y_r2 { get; set; }
        public string lms_x_r3 { get; set; }
        public string lms_y_r3 { get; set; }
        public string lnms_x_r3 { get; set; }
        public string lnms_y_r3 { get; set; }
        public string lf_x_r3 { get; set; }
        public string lf_y_r3 { get; set; }
    }
}
