//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_seagate_copperwire_coverpage
    {
        public int ID { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> specification_id { get; set; }
        public string procedureNo { get; set; }
        public string number_of_pieces_used_for_extraction { get; set; }
        public string copper_wire_corrosion_test { get; set; }
        public string specification_limit { get; set; }
        public string result { get; set; }
        public string result2 { get; set; }
        public string result3 { get; set; }
    }
}
