//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_seagate_gcms_coverpage_img
    {
        public int id { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> img_type { get; set; }
        public string path_img1 { get; set; }
    }
}
