//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_seagate_mesa_coverpage
    {
        public int ID { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> component_id { get; set; }
        public string location_of_parts { get; set; }
        public string specification { get; set; }
        public string result { get; set; }
        public string pass_fail { get; set; }
        public string ProcedureNo_Extraction { get; set; }
        public string ExtractionMedium_Extraction { get; set; }
        public string SampleSize_Extraction { get; set; }
        public string OvenCondition_Extraction { get; set; }
        public string ProcedureNo_IndirectMaterials { get; set; }
        public string SampleSize_IndirectMaterials { get; set; }
        public string OvenCondition_IndirectMaterials { get; set; }
        public Nullable<int> row_type { get; set; }
    }
}
