//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_seagate_gcms_coverpage
    {
        public int ID { get; set; }
        public Nullable<int> component_id { get; set; }
        public string procedure_no { get; set; }
        public Nullable<int> sample_id { get; set; }
        public string sample_size { get; set; }
        public string extraction_medium { get; set; }
        public string extraction_volumn { get; set; }
        public Nullable<int> UnitMotorOilContamination { get; set; }
        public Nullable<int> UnitMotorHub { get; set; }
        public Nullable<int> UnitMotorHubSub { get; set; }
        public Nullable<int> UnitMotorBase { get; set; }
        public Nullable<int> UnitMotorBaseSub { get; set; }
        public Nullable<int> UnitCompound { get; set; }
        public Nullable<int> row_type { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string B13 { get; set; }
        public string B14 { get; set; }
        public string B15 { get; set; }
        public string B16 { get; set; }
        public string B17 { get; set; }
        public string B18 { get; set; }
        public string B19 { get; set; }
        public string B20 { get; set; }
        public string B21 { get; set; }
        public string B22 { get; set; }
        public string B23 { get; set; }
        public string B24 { get; set; }
        public string B25 { get; set; }
        public string B26 { get; set; }
        public string B27 { get; set; }
        public string B28 { get; set; }
        public string B29 { get; set; }
        public string B30 { get; set; }
        public string B31 { get; set; }
        public string B32 { get; set; }
        public string B34 { get; set; }
        public string B35 { get; set; }
        public string B36 { get; set; }
        public string B39 { get; set; }
        public string B40 { get; set; }
        public string B41 { get; set; }
        public string B42 { get; set; }
        public string B43 { get; set; }
        public string B44 { get; set; }
        public string B45 { get; set; }
        public string B46 { get; set; }
        public string B47 { get; set; }
        public string B48 { get; set; }
        public string B49 { get; set; }
        public string B50 { get; set; }
        public string B51 { get; set; }
        public string B52 { get; set; }
        public string C40 { get; set; }
        public string C41 { get; set; }
        public string C42 { get; set; }
        public string B53 { get; set; }
        public string B54 { get; set; }
        public string B55 { get; set; }
        public string B56 { get; set; }
        public string B57 { get; set; }
        public string B58 { get; set; }
        public string B59 { get; set; }
        public string B60 { get; set; }
        public string B61 { get; set; }
        public string B62 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public string C30 { get; set; }
        public string C31 { get; set; }
        public string C32 { get; set; }
        public string C34 { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public string C43 { get; set; }
        public string C44 { get; set; }
        public string C45 { get; set; }
        public string C46 { get; set; }
        public string C47 { get; set; }
        public string C48 { get; set; }
        public string C49 { get; set; }
        public string C50 { get; set; }
        public string C51 { get; set; }
        public string C52 { get; set; }
        public string D40 { get; set; }
        public string D41 { get; set; }
        public string D42 { get; set; }
        public string D43 { get; set; }
        public string D44 { get; set; }
        public string D45 { get; set; }
        public string D46 { get; set; }
        public string D47 { get; set; }
        public string D48 { get; set; }
        public string D49 { get; set; }
        public string D50 { get; set; }
        public string D51 { get; set; }
        public string D52 { get; set; }
        public Nullable<int> selected_base { get; set; }
        public Nullable<int> data_type { get; set; }
        public string C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C29 { get; set; }
        public string D20 { get; set; }
        public string D21 { get; set; }
        public string D22 { get; set; }
        public string D23 { get; set; }
        public string D24 { get; set; }
        public string D25 { get; set; }
        public string D26 { get; set; }
        public string D27 { get; set; }
        public string D28 { get; set; }
        public string D29 { get; set; }
        public string D30 { get; set; }
        public string D31 { get; set; }
        public string D32 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string E20 { get; set; }
        public string E21 { get; set; }
        public string E22 { get; set; }
        public string E23 { get; set; }
        public string E24 { get; set; }
        public string E25 { get; set; }
        public string E26 { get; set; }
        public string E27 { get; set; }
        public string E28 { get; set; }
        public string E29 { get; set; }
        public string E30 { get; set; }
        public string E31 { get; set; }
        public string E32 { get; set; }
        public string F20 { get; set; }
        public string F21 { get; set; }
        public string F22 { get; set; }
        public string F23 { get; set; }
        public string F24 { get; set; }
        public string F25 { get; set; }
        public string F26 { get; set; }
        public string F27 { get; set; }
        public string F28 { get; set; }
        public string F29 { get; set; }
        public string F30 { get; set; }
        public string F31 { get; set; }
        public string F32 { get; set; }
        public string C13 { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public Nullable<int> UnitCompoundSub { get; set; }
    }
}
