//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_wd_gcms_coverpage
    {
        public int ID { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> component_id { get; set; }
        public Nullable<int> detail_spec_id { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public Nullable<int> row_type { get; set; }
        public string pm_procedure { get; set; }
        public string pm_number_of_pieces { get; set; }
        public string pm_extraction_medium { get; set; }
        public string pm_extraction_volumn { get; set; }
        public string pm_unit { get; set; }
        public Nullable<int> test { get; set; }
    }
}
