//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_wd_hpa_for1_coverpage
    {
        public int ID { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> detail_spec_id { get; set; }
        public Nullable<int> component_id { get; set; }
        public Nullable<int> seq { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public Nullable<int> C { get; set; }
        public string D { get; set; }
        public string E { get; set; }
        public Nullable<int> row_type { get; set; }
        public Nullable<int> parent { get; set; }
        public string img_path { get; set; }
        public string ParticleAnalysisBySEMEDX { get; set; }
        public string TapedAreaForDriveParts { get; set; }
        public string NoofTimesTaped { get; set; }
        public string SurfaceAreaAnalysed { get; set; }
        public string ParticleRanges { get; set; }
        public string unit { get; set; }
    }
}
