//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.ALSI.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_login
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> latest_login { get; set; }
        public string email { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string status { get; set; }
        public string responsible_test { get; set; }
        public Nullable<bool> is_force_change_password { get; set; }
        public Nullable<int> personal_title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile_phone { get; set; }
    
        public virtual m_title m_title { get; set; }
        public virtual role role { get; set; }
    }
}
