ALTER TABLE `alsi`.`tb_m_component` 
ADD COLUMN `status` VARCHAR(1) NULL AFTER `Z`;

ALTER TABLE `alsi`.`job_sample` 
ADD COLUMN `note_lab1` VARCHAR(45) NULL AFTER `note_lab`;

update tb_m_component set status='A';

------
CREATE TABLE holiday_calendar
( 
  DATE_HOLIDAYS DATE NOT NULL ,
  YEAR_HOLIDAYS VARCHAR(4) NOT NULL ,
  DESCRIPTION_SUMMARY VARCHAR(255)
);


INSERT INTO holiday_calendar (DESCRIPTION_SUMMARY,DATE_HOLIDAYS,YEAR_HOLIDAYS) 
SELECT * FROM (
SELECT 'วันขึ้นปีใหม่' DESCRIPTION_SUMMARY,'2018-1-1' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'ชดเชยวันสิ้นปี' DESCRIPTION_SUMMARY,'2018-1-2' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันมาฆบูชา' DESCRIPTION_SUMMARY,'2018-1-3' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันจักรี' DESCRIPTION_SUMMARY,'2018-4-6' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันสงกรานต์' DESCRIPTION_SUMMARY,'2018-4-13' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันสงกรานต์' DESCRIPTION_SUMMARY,'2018-4-14' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันสงกรานต์' DESCRIPTION_SUMMARY,'2018-4-15' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันหยุดชดเชยวันสงกรานต์' DESCRIPTION_SUMMARY,'2018-4-16' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันแรงงาน' DESCRIPTION_SUMMARY,'2018-5-1' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันพืชมงคล' DESCRIPTION_SUMMARY,'2018-5-14' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันวิสาขบูชา' DESCRIPTION_SUMMARY,'2018-5-29' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันอาสาฬหบูชา' DESCRIPTION_SUMMARY,'2018-7-27' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันเฉลิมพระชนมพรรษา สมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร (ร.10) และวันเข้าพรรษา' DESCRIPTION_SUMMARY,'2018-7-28' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันหยุดชดเชยวันเฉลิมพระชนมพรรษา สมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร (ร.10)' DESCRIPTION_SUMMARY,'2018-7-30' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันแม่แห่งชาติ' DESCRIPTION_SUMMARY,'2018-8-12' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันหยุดชดเชยวันแม่แห่งชาติ' DESCRIPTION_SUMMARY,'2018-8-13' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันคล้ายวันสวรรคต พระบาทสมเด็จพระเจ้าอยู่หัวภูมิพลอดุลยเดช (ร.9)' DESCRIPTION_SUMMARY,'2018-10-13' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันหยุดชดเชยวันคล้ายวันสวรรคต พระบาทสมเด็จพระเจ้าอยู่หัวภูมิพลอดุลยเดช (ร.9)' DESCRIPTION_SUMMARY,'2018-10-15' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันปิยมหาราช' DESCRIPTION_SUMMARY,'2018-10-23' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันคล้ายวันพระบรมราชสมภพ พระบาทสมเด็จพระเจ้าอยู่หัวภูมิพลอดุลยเดช (ร.9), วันชาติ และวันพ่อแห่งชาติ' DESCRIPTION_SUMMARY,'2018-12-05' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันรัฐธรรมนูญ' DESCRIPTION_SUMMARY,'2018-12-10' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS UNION
SELECT 'วันสิ้นปี' DESCRIPTION_SUMMARY,'2018-12-31' DATE_HOLIDAYS,'2018' YEAR_HOLIDAYS
)tmp
WHERE NOT EXISTS(
	SELECT 1 FROM holiday_calendar APH
	WHERE APH.holiday_calendar = tmp.DATE_HOLIDAYS
 );

CREATE INDEX IDX_holiday_calendar ON holiday_calendar (DATE_HOLIDAYS);