INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('3','Choltinee Tangtreerat ','+66 81 170 7109','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('4','Anusorn Chakkaew','+66 85 441 9193','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('5','Witoon Ponglaohapun','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('6','Atthakorn Termpittayapaisit','+66 81 321 4264','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('7','Waraporn Pholyiem','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('8','Kanokwan','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('9','Pisit Rujipichapornkul','+66 83 135 8998','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('10','Ittthikorn Jinuntuya','+66 86 688 8341','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('11','Yutthana','+66 86 565 7231','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('12','Nongluk','+66 86 105 8722','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('13','Waleepun Kaewpatch','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('14','Jeeranan Pimta','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('15','Onnisara Archariya','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('16','Saengtean','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('17','Martin Covell','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('18','Puntharee Sirojtantikorn','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('19','Runglawan Seeburth','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('20','Walaipon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('21','Patpong  Boonraksah','+66 83 899 6346','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('22','Panachon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('23','Sukanya Prasertsung ','+66 89 920 3494','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('24','Sukanya Chantaworakit ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('25','Charnchai Jamrasfuangfoo','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('26','Bantita Takkhapiwat (Kate)','+66 85 111 6710','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('27','Chairat Luepongpattana','+66 86 873 8006','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('28','Jiraporn Somnuam','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('29','Nataporn  Phunnarungsi','+66 81 840 5083','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('30','Vanida Keswong','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('31','Kanuengnit','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('32','Sunanta Sukpool','+66 89 066 3125','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('33','Patchara Toprated','+66 84 094 4633','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('34','Rungnapa Pasuriwong','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('35','Thiraporn Yaiying (Pu)','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('36','Sakranta Tonsanguan','+66 94 651 4664','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('37','Warut Sutjaritjun','+66 86 125 5152','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('38','Natnapat Methanorapat ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('39','Kampol','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('40','Pacharathon Chueateaw','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('41','Patipat','+66 81 988 3996','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('42','Yeamyuth  Manitras','+66 81 945 5833','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('43','Wannuttee Malithong ','+66 86 993 2026','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('44','Yuthtaphoom Silachan','+66 81-639 0394','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('45','Aree Krataitong','+66 89 814 2276','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('46','Usani','+66 87 9711959','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('47','Kristoffer Clyde G. Magsino (Clyde)','+66 89 767 0202','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('48','Pornpit Phetrak','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('49','Netnapa Y. ( Yui)','+66 81 555 8659','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('50','Namphung Feepakprao','+66 86 972 6138 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('51','Daranee Phoyu','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('52','Surasak Kornnitikul','+66 86 030 0398','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('53','Uthen Wiriyakasikon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('54','Patthamon   Kittisophon ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('55','Supansa  Noinamkam','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('56','Amornchai','+66 86 345 6553','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('57','Sudarat (Art)','+66 89 900 9413','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('58','Nitjawan Inthajakr ','+66 81 931 2166 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('59','Doungdao Phanthong','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('60','Sakchai','+66 81 840 5389','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('61','Tula Chankana','+66 81 939 2808','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('62','Patinya  Pansuk ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('63','Sukanya Yujan (Su)','+66 87 201 9195 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('64','Sittiporn','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('65','Warunya','+66 90 961 3636','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('66','Aniruth Uthaisawek','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('67','Suriam','+66 86 523 6555','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('68','Supaktra Sa-Nguanrat','+66 81 754 9808','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('69','Mana','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('70','Mana','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('71','Sarisanach Iamsripeng','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('72','Panachon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('73','Sompong Suphap','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('74','Saleela','+66 86 320 6456','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('75','Wuttichai  Chamnan','+66 85 071 1626','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('76','Bancha','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('77','Sutthipong Itthipalangkul ','+66 85 109 5682 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('78','Dusit Suratham','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('79','Dusit Suratham','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('80','Jariya  Makan  (Sai)','+66 87 859 0620','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('81','Kittichai Pinwiset','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('82','Teerawat','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('83','Charida','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('84','Pallapa Rattanawaraporn ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('85','Daungrutai Boonyen','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('86','Suphoj Cholkujanan','+66 81 854 5843','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('87','Wivornchai  Boonyon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('88','Sutheera','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('89','Daungnapa','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('90','Noppawan Jomkamsing','+66 89 666 3097','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('91','Nuantip Tanya','+66 81 694 3804','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('92','Nithima Pimpijit','+66 87 517 8490','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('93','Darunee Aussawasathien','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('94','Pornpimol','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('95','Sasipapha  Ruang U-Rai (Rin)','+66 89 923 3156','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('96','Piyachat','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('97','Put Sae-Lew','+66 90 429 5861','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('98','Jutharat   Phonkaew','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('99','Kittisak Pandaranandaka','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('100','Suwimon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('101','Siranee Songsawas','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('102','Pratchapol Marutapun','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('103','Mattika Sri-On','+66 86 001 7870','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('104','Jiratchaya Sae-Lim','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('105','Rungthiwa  Buatoom (Daeng)','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('106','Naruemon Pinthong','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('107','Somkid Pichi  ( Aoy ) ','+66 87 916 5343','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('108','Alisa  Dararung','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('109','Nipaporn Muangnak ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('110','Charnchai Jamrasfuangfoo','+66 89 922 8459','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('111','Janeth A. Mallorca','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('112','Bongkot Chaipiwong (Pom)','+66 81 172 3247','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('113','Aktana','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('114','Ammarin','+66 91 557 8690','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('115','Numtip Sangchai','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('116','Somsak','+66 81 811 6057','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('117','Hattaya Aranyanarth','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('118','Kittipong','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('119','Wilaiporn','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('120','Achara','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('121','Praphaporn  K. (อ้วน ) ','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('122','Daw Petchsri','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('123','Wijittra Mokchai(Angie)','+66 95 535 1448','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('124','Kanok','+66 86 361  0647','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('125','Jutima Phonchalard','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('126','Sakpaiboon Tajumpa','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('127','Suparat Yangsanthia','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('128','Kitti Kaewrattanapattama','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('129','Hunsa Opanuruk','+66 86 677 7697','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('130','Chiraporn','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('131','Chanukid Siripakornchai','+66 81 648 5545 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('132','Pinanong','+66 89 734 3620','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('133','Kantinunt Supsermpol','+66 86 977 7416','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('134','Kantinunt Supsermpol','+66 86 977 7416','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('135','Rattana  Bandasak','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('136','Somchok','+66 81 913 2684','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('137','Sirichai Ratthanaphuripat','+66 90 198 7801 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('138','Worawun Thiwunnarak','+66 81 916 5824','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('139','Sayfon  Wangkeeree ','+66 86 753 2179','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('140','Pairoge Wongsakulchuen','+66 81 812 3967','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('141','Nuntaporn Krasaesut','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('142','Angsana Phummee','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('143','Yhutapol  Tommahon','+66 82 120 5685     ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('144','Nantakan Klongduangjit','+66 92 617 7789','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('145','Wanyupa  Waikulpech','+66 85 482 9426','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('146','Niramol','+66 89 244 7006','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('147','Tassanee','+66 81 999 5913','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('148','Rungrapee Boonmee','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('149','Rattiya Tangyoo ','+66 83 123 4684','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('150','Noboru Hayakawa ','+66 80 603 2417','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('151','Sophie Zhou','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('152','Aree  Boonpa','+66 81 714 9685','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('153','Thawatchai','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('154','Kittisak','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('155','Udaporn  Phookduang (Gap)','+66 89 403 9293 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('156','Wendy Wee','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('157','Achari Saardiem','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('158','Patcharapong','+66 81 786 1639','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('159','Patcharapong','+66 81 786 1639','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('160','Gusmar Thungsupanich','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('161','Wassana','+66 86 546 3205','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('162','Teeraphan','+66 81 825 3667','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('163','Nattamon','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('164','Yutthana','+66 81 910 2013 ','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('165','Piyapong Inthaphophan','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('166','Thanawat Taweeprecharat ','+66 84 075 3668','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('167','Somporn','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('168','Sakuna Chongkittisakul','+66 86 754 5268','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('169','Kingfa Kitchainugool','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('170','Chonchalerm Suwannapho ','+66 81 863 3660','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('171','Usani','+66 87 9711959','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('172','Usani','+66 87 9711959','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('173','Chitlrapat','+66 86 774 3233','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('174','Thitima','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('175','Shousuke Takahashi','','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('176','Kongsak Sanguanpong','+66 86 309 3330','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('177','Korawan  Sowichai','+66 96 416 2469','A');
INSERT INTO m_customer_contract_person(company_id,name,phone_number,status) VALUES('178','Sawek Chaisalee','+66 86 654 7601','A');

