CREATE TABLE `template_seagate_ftir_coverpage` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `sample_id` int(11) DEFAULT NULL,
  `specification_id` int(11) DEFAULT NULL,
`w_b13` varchar(45) DEFAULT NULL,
`w_b14` varchar(45) DEFAULT NULL,
`w_b15` varchar(45) DEFAULT NULL,
`w_b20` varchar(45) DEFAULT NULL,
`w_C20` varchar(45) DEFAULT NULL,
`w_d20` varchar(45) DEFAULT NULL,
`w_e20` varchar(45) DEFAULT NULL,
`w_b21` varchar(45) DEFAULT NULL,
`w_C21` varchar(45) DEFAULT NULL,
`w_d21` varchar(45) DEFAULT NULL,
`w_e21` varchar(45) DEFAULT NULL,
`w_b22` varchar(45) DEFAULT NULL,
`w_C22` varchar(45) DEFAULT NULL,
`w_d22` varchar(45) DEFAULT NULL,
`w_e22` varchar(45) DEFAULT NULL,
`w_b24` varchar(45) DEFAULT NULL,
`w_C24` varchar(45) DEFAULT NULL,
`w_d24` varchar(45) DEFAULT NULL,
`w_e24` varchar(45) DEFAULT NULL,
`w_b26` varchar(45) DEFAULT NULL,
`w_C26` varchar(45) DEFAULT NULL,
`w_d26` varchar(45) DEFAULT NULL,
`w_e26` varchar(45) DEFAULT NULL,
`w_b27` varchar(45) DEFAULT NULL,
`w_C27` varchar(45) DEFAULT NULL,
`w_d27` varchar(45) DEFAULT NULL,
`w_e27` varchar(45) DEFAULT NULL,


`lfu_b13` varchar(45) DEFAULT NULL,
`lfu_b14` varchar(45) DEFAULT NULL,
`lfu_b15` varchar(45) DEFAULT NULL,
`lfu_b20` varchar(45) DEFAULT NULL,
`lfu_c20` varchar(45) DEFAULT NULL,
`lfu_d20` varchar(45) DEFAULT NULL,
`lfu_e20` varchar(45) DEFAULT NULL,
`lfu_b21` varchar(45) DEFAULT NULL,
`lfu_c21` varchar(45) DEFAULT NULL,
`lfu_d21` varchar(45) DEFAULT NULL,
`lfu_e21` varchar(45) DEFAULT NULL,
`lfu_b22` varchar(45) DEFAULT NULL,
`lfu_c22` varchar(45) DEFAULT NULL,
`lfu_d22` varchar(45) DEFAULT NULL,
`lfu_e22` varchar(45) DEFAULT NULL,
`lfu_b24` varchar(45) DEFAULT NULL,
`lfu_c24` varchar(45) DEFAULT NULL,
`lfu_d24` varchar(45) DEFAULT NULL,
`lfu_e24` varchar(45) DEFAULT NULL,
`lfu_b26` varchar(45) DEFAULT NULL,
`lfu_c26` varchar(45) DEFAULT NULL,
`lfu_d26` varchar(45) DEFAULT NULL,
`lfu_e26` varchar(45) DEFAULT NULL,
`lfu_b27` varchar(45) DEFAULT NULL,
`lfu_c27` varchar(45) DEFAULT NULL,
`lfu_d27` varchar(45) DEFAULT NULL,
`lfu_e27` varchar(45) DEFAULT NULL,

`ldu_b13` varchar(45) DEFAULT NULL,
`ldu_b14` varchar(45) DEFAULT NULL,
`ldu_b15` varchar(45) DEFAULT NULL,
`ldu_b20` varchar(45) DEFAULT NULL,
`ldu_c20` varchar(45) DEFAULT NULL,
`ldu_d20` varchar(45) DEFAULT NULL,
`ldu_e20` varchar(45) DEFAULT NULL,
`ldu_b21` varchar(45) DEFAULT NULL,
`ldu_c21` varchar(45) DEFAULT NULL,
`ldu_d21` varchar(45) DEFAULT NULL,
`ldu_e21` varchar(45) DEFAULT NULL,
`ldu_b22` varchar(45) DEFAULT NULL,
`ldu_c22` varchar(45) DEFAULT NULL,
`ldu_d22` varchar(45) DEFAULT NULL,
`ldu_e22` varchar(45) DEFAULT NULL,
`ldu_b24` varchar(45) DEFAULT NULL,
`ldu_c24` varchar(45) DEFAULT NULL,
`ldu_d24` varchar(45) DEFAULT NULL,
`ldu_e24` varchar(45) DEFAULT NULL,
`ldu_b26` varchar(45) DEFAULT NULL,
`ldu_c26` varchar(45) DEFAULT NULL,
`ldu_d26` varchar(45) DEFAULT NULL,
`ldu_e26` varchar(45) DEFAULT NULL,
`ldu_b27` varchar(45) DEFAULT NULL,
`ldu_c27` varchar(45) DEFAULT NULL,
`ldu_d27` varchar(45) DEFAULT NULL,
`ldu_e27` varchar(45) DEFAULT NULL,

  `item_visible` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_sample_idx_2_idx` (`sample_id`),
  KEY `fk_specification_id_idx_2_idx` (`specification_id`),
  CONSTRAINT `fk_sample_idx_2` FOREIGN KEY (`sample_id`) REFERENCES `job_sample` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_specification_id_idx_2` FOREIGN KEY (`specification_id`) REFERENCES `tb_m_ftir_specification` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
